// <auto-generated />
using Blackjack21Zhilin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blackjack21Zhilin.Migrations
{
    [DbContext(typeof(Blackjack21ZhilinContext))]
    [Migration("20200530202534_Add-Migration InitialUpdate")]
    partial class AddMigrationInitialUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blackjack21Zhilin.Models.PlayCard", b =>
                {
                    b.Property<int>("PlayCardId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDistributed");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhotoPath")
                        .IsRequired();

                    b.Property<int>("PlayerId");

                    b.Property<int>("Value");

                    b.HasKey("PlayCardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayCard");
                });

            modelBuilder.Entity("Blackjack21Zhilin.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("PlayerId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Blackjack21Zhilin.Models.PlayCard", b =>
                {
                    b.HasOne("Blackjack21Zhilin.Models.Player", "Player")
                        .WithMany("PlayCards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
